import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { site } from '@/data/content';

// Tall condensed display font. (Bebas_Neue from next/font/google is a drop-in alternative.)
const display = localFont({ src: '../public/fonts/anton.woff2', variable: '--font-display', weight: '400', display: 'swap' });
const heroFont = localFont({ src: [
  { path: '../public/fonts/poppins-400.woff2', weight: '400' },
  { path: '../public/fonts/poppins-500.woff2', weight: '500' },
  { path: '../public/fonts/poppins-600.woff2', weight: '600' },
], variable: '--font-hero', display: 'swap' });
const chunk = localFont({ src: '../public/fonts/dela-gothic-one.woff2', variable: '--font-chunk', weight: '400', display: 'swap' });
const grotesk = localFont({ src: '../public/fonts/space-grotesk.woff2', variable: '--font-grotesk', weight: '500 600', display: 'swap' });
const body = localFont({ src: '../public/fonts/inter.woff2', variable: '--font-body', weight: '100 900', display: 'swap' });

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: { default: `${site.name} — ${site.role}`, template: `%s · ${site.name}` },
  description: site.description,
  keywords: site.keywords,
  authors: [{ name: site.name }],
  creator: site.name,
  alternates: { canonical: '/' },
  openGraph: {
    type: 'website',
    url: site.url,
    siteName: site.name,
    title: `${site.name} — ${site.role}`,
    description: site.description,
    // The image itself is generated by app/opengraph-image.tsx
  },
  twitter: { card: 'summary_large_image', title: `${site.name} — ${site.role}`, description: site.description },
  robots: { index: true, follow: true },
};

export const viewport: Viewport = {
  themeColor: '#E8500A',
  width: 'device-width',
  initialScale: 1,
};

const jsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Person',
  name: site.name,
  jobTitle: site.role,
  url: site.url,
  description: site.description,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${display.variable} ${body.variable} ${heroFont.variable} ${chunk.variable} ${grotesk.variable}`} data-phase="loading">
      <body>
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
        {children}
      </body>
    </html>
  );
}
